/*

The MIT License (MIT)

Copyright (c) 2014 Guillermo Rauch


Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. Socket.IO v2.1.1
 (c) 2014-2018 Guillermo Rauch
 Released under the MIT License.
 https://mths.be/utf8js v2.1.2 by @mathias */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(n){var g=0;return function(){return g<n.length?{done:!1,value:n[g++]}:{done:!0}}};$jscomp.arrayIterator=function(n){return{next:$jscomp.arrayIteratorImpl(n)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(n,g,e){if(n==Array.prototype||n==Object.prototype)return n;n[g]=e.value;return n};$jscomp.getGlobal=function(n){n=["object"==typeof globalThis&&globalThis,n,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<n.length;++g){var e=n[g];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(n,g){var e=$jscomp.propertyToPolyfillSymbol[g];if(null==e)return n[g];e=n[e];return void 0!==e?e:n[g]};
$jscomp.polyfill=function(n,g,e,c){g&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(n,g,e,c):$jscomp.polyfillUnisolated(n,g,e,c))};$jscomp.polyfillUnisolated=function(n,g,e,c){e=$jscomp.global;n=n.split(".");for(c=0;c<n.length-1;c++){var d=n[c];if(!(d in e))return;e=e[d]}n=n[n.length-1];c=e[n];g=g(c);g!=c&&null!=g&&$jscomp.defineProperty(e,n,{configurable:!0,writable:!0,value:g})};
$jscomp.polyfillIsolated=function(n,g,e,c){var d=n.split(".");n=1===d.length;c=d[0];c=!n&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var h=d[f];if(!(h in c))return;c=c[h]}d=d[d.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?c[d]:null;g=g(e);null!=g&&(n?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:g}):g!==e&&(void 0===$jscomp.propertyToPolyfillSymbol[d]&&(e=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+e+"$"+d),$jscomp.defineProperty(c,$jscomp.propertyToPolyfillSymbol[d],{configurable:!0,writable:!0,value:g})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(n){if(n)return n;var g=function(f,h){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:h})};g.prototype.toString=function(){return this.$jscomp$symbol$id_};var e="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",c=0,d=function(f){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new g(e+(f||"")+"_"+c++,f)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(n){if(n)return n;n=Symbol("Symbol.iterator");for(var g="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<g.length;e++){var c=$jscomp.global[g[e]];"function"===typeof c&&"function"!=typeof c.prototype[n]&&$jscomp.defineProperty(c.prototype,n,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return n},"es6",
"es3");$jscomp.iteratorPrototype=function(n){n={next:n};n[Symbol.iterator]=function(){return this};return n};$jscomp.iteratorFromArray=function(n,g){n instanceof String&&(n+="");var e=0,c=!1,d={next:function(){if(!c&&e<n.length){var f=e++;return{value:g(f,n[f]),done:!1}}c=!0;return{done:!0,value:void 0}}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(n){return n?n:function(){return $jscomp.iteratorFromArray(this,function(g){return g})}},"es6","es3");
(function(n,g){"object"===typeof exports&&"object"===typeof module?module.exports=g():"function"===typeof define&&define.amd?define([],g):"object"===typeof exports?exports.io=g():n.io=g()})(this,function(){return function(n){function g(c){if(e[c])return e[c].exports;var d=e[c]={exports:{},id:c,loaded:!1};n[c].call(d.exports,d,d.exports,g);d.loaded=!0;return d.exports}var e={};g.m=n;g.c=e;g.p="";return g(0)}([function(n,g,e){function c(t,r){"object"===("undefined"===typeof t?"undefined":d(t))&&(r=
t,t=void 0);r=r||{};t=f(t,null,r.path||"/socket.io");var k=t.source,a=t.id,b=t.path;b=u[a]&&b in u[a].nsps;r.forceNew||r["force new connection"]||!1===r.multiplex||b?(v("ignoring socket cache for %s",k),k=p(k,r)):(u[a]||(v("new io instance for %s",k),u[a]=p(k,r)),k=u[a]);t.query&&!r.query&&(r.query=t.query);return k.socket(t.path,r)}var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"===typeof Symbol&&t.constructor===Symbol&&
t!==Symbol.prototype?"symbol":typeof t},f=e(1),h=e(7),p=e(12),v=e(3)("socket.io-client");n.exports=g=c;var u=g.managers={};g.protocol=h.protocol;g.connect=c;g.Manager=e(12);g.Socket=e(37)},function(n,g,e){(function(c){var d=e(2),f=e(3)("socket.io-client:url");n.exports=function(h,p,v){var u=h;p=p||c.location;null==h&&(h=p.protocol+"//"+p.host);"string"===typeof h&&("/"===h.charAt(0)&&(h="/"===h.charAt(1)?p.protocol+h:p.host+h),/^(https?|wss?):\/\//.test(h)||(f("protocol-less url %s",h),h="undefined"!==
typeof p?p.protocol+"//"+h:"https://"+h),f("parse %s",h),u=d(h));u.port||(/^(http|ws)$/.test(u.protocol)?u.port="80":/^(http|ws)s$/.test(u.protocol)&&(u.port="443"));u.path=u.path||"/";h=-1!==u.host.indexOf(":")?"["+u.host+"]":u.host;u.id=u.protocol+"://"+h+":"+u.port+v;u.href=u.protocol+"://"+h+(p&&p.port===u.port?"":":"+u.port);return u}}).call(g,function(){return this}())},function(n,g){var e=/^(?:(?![^:@]+:[^:@\/]*@)(http|https|ws|wss):\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?((?:[a-f0-9]{0,4}:){2,7}[a-f0-9]{0,4}|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,
c="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");n.exports=function(d){var f=d,h=d.indexOf("["),p=d.indexOf("]");-1!=h&&-1!=p&&(d=d.substring(0,h)+d.substring(h,p).replace(/:/g,";")+d.substring(p,d.length));d=e.exec(d||"");for(var v={},u=14;u--;)v[c[u]]=d[u]||"";-1!=h&&-1!=p&&(v.source=f,v.host=v.host.substring(1,v.host.length-1).replace(/;/g,":"),v.authority=v.authority.replace("[","").replace("]","").replace(/;/g,":"),v.ipv6uri=
!0);return v}},function(n,g,e){(function(c){function d(){try{var p=g.storage.debug}catch(v){}!p&&"undefined"!==typeof c&&"env"in c&&(p=c.env.DEBUG);return p}g=n.exports=e(5);g.log=function(){return"object"===typeof console&&console.log&&Function.prototype.apply.call(console.log,console,arguments)};g.formatArgs=function(p){var v=this.useColors;p[0]=(v?"%c":"")+this.namespace+(v?" %c":" ")+p[0]+(v?"%c ":" ")+"+"+g.humanize(this.diff);if(v){v="color: "+this.color;p.splice(1,0,v,"color: inherit");var u=
0,t=0;p[0].replace(/%[a-zA-Z%]/g,function(r){"%%"!==r&&(u++,"%c"===r&&(t=u))});p.splice(t,0,v)}};g.save=function(p){try{null==p?g.storage.removeItem("debug"):g.storage.debug=p}catch(v){}};g.load=d;g.useColors=function(){return"undefined"!==typeof window&&window.process&&"renderer"===window.process.type?!0:"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/(edge|trident)\/(\d+)/)?!1:"undefined"!==typeof document&&document.documentElement&&document.documentElement.style&&
document.documentElement.style.WebkitAppearance||"undefined"!==typeof window&&window.console&&(window.console.firebug||window.console.exception&&window.console.table)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/firefox\/(\d+)/)&&31<=parseInt(RegExp.$1,10)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/applewebkit\/(\d+)/)};var f=g;if("undefined"!=typeof chrome&&"undefined"!=typeof chrome.storage)var h=
chrome.storage.local;else a:{try{h=window.localStorage;break a}catch(p){}h=void 0}f.storage=h;g.colors="#0000CC #0000FF #0033CC #0033FF #0066CC #0066FF #0099CC #0099FF #00CC00 #00CC33 #00CC66 #00CC99 #00CCCC #00CCFF #3300CC #3300FF #3333CC #3333FF #3366CC #3366FF #3399CC #3399FF #33CC00 #33CC33 #33CC66 #33CC99 #33CCCC #33CCFF #6600CC #6600FF #6633CC #6633FF #66CC00 #66CC33 #9900CC #9900FF #9933CC #9933FF #99CC00 #99CC33 #CC0000 #CC0033 #CC0066 #CC0099 #CC00CC #CC00FF #CC3300 #CC3333 #CC3366 #CC3399 #CC33CC #CC33FF #CC6600 #CC6633 #CC9900 #CC9933 #CCCC00 #CCCC33 #FF0000 #FF0033 #FF0066 #FF0099 #FF00CC #FF00FF #FF3300 #FF3333 #FF3366 #FF3399 #FF33CC #FF33FF #FF6600 #FF6633 #FF9900 #FF9933 #FFCC00 #FFCC33".split(" ");
g.formatters.j=function(p){try{return JSON.stringify(p)}catch(v){return"[UnexpectedJSONParseError]: "+v.message}};g.enable(d())}).call(g,e(4))},function(n,g){function e(){throw Error("setTimeout has not been defined");}function c(){throw Error("clearTimeout has not been defined");}function d(m){if(t===setTimeout)return setTimeout(m,0);if((t===e||!t)&&setTimeout)return t=setTimeout,setTimeout(m,0);try{return t(m,0)}catch(w){try{return t.call(null,m,0)}catch(B){return t.call(this,m,0)}}}function f(m){if(r===
clearTimeout)return clearTimeout(m);if((r===c||!r)&&clearTimeout)return r=clearTimeout,clearTimeout(m);try{return r(m)}catch(w){try{return r.call(null,m)}catch(B){return r.call(this,m)}}}function h(){a&&b&&(a=!1,b.length?k=b.concat(k):l=-1,k.length&&p())}function p(){if(!a){var m=d(h);a=!0;for(var w=k.length;w;){b=k;for(k=[];++l<w;)b&&b[l].run();l=-1;w=k.length}b=null;a=!1;f(m)}}function v(m,w){this.fun=m;this.array=w}function u(){}n=n.exports={};try{var t="function"===typeof setTimeout?setTimeout:
e}catch(m){t=e}try{var r="function"===typeof clearTimeout?clearTimeout:c}catch(m){r=c}var k=[],a=!1,b,l=-1;n.nextTick=function(m){var w=Array(arguments.length-1);if(1<arguments.length)for(var B=1;B<arguments.length;B++)w[B-1]=arguments[B];k.push(new v(m,w));1!==k.length||a||d(p)};v.prototype.run=function(){this.fun.apply(null,this.array)};n.title="browser";n.browser=!0;n.env={};n.argv=[];n.version="";n.versions={};n.on=u;n.addListener=u;n.once=u;n.off=u;n.removeListener=u;n.removeAllListeners=u;n.emit=
u;n.prependListener=u;n.prependOnceListener=u;n.listeners=function(m){return[]};n.binding=function(m){throw Error("process.binding is not supported");};n.cwd=function(){return"/"};n.chdir=function(m){throw Error("process.chdir is not supported");};n.umask=function(){return 0}},function(n,g,e){function c(h){var p=0,v;for(v in h)p=(p<<5)-p+h.charCodeAt(v),p|=0;return g.colors[Math.abs(p)%g.colors.length]}function d(h){function p(){if(p.enabled){var u=+new Date;p.diff=u-(v||u);p.prev=v;v=p.curr=u;var t=
Array(arguments.length);for(u=0;u<t.length;u++)t[u]=arguments[u];t[0]=g.coerce(t[0]);"string"!==typeof t[0]&&t.unshift("%O");var r=0;t[0]=t[0].replace(/%([a-zA-Z%])/g,function(k,a){if("%%"===k)return k;r++;a=g.formatters[a];"function"===typeof a&&(k=a.call(p,t[r]),t.splice(r,1),r--);return k});g.formatArgs.call(p,t);(p.log||g.log||console.log.bind(console)).apply(p,t)}}var v;p.namespace=h;p.enabled=g.enabled(h);p.useColors=g.useColors();p.color=c(h);p.destroy=f;"function"===typeof g.init&&g.init(p);
g.instances.push(p);return p}function f(){var h=g.instances.indexOf(this);return-1!==h?(g.instances.splice(h,1),!0):!1}g=n.exports=d.debug=d["default"]=d;g.coerce=function(h){return h instanceof Error?h.stack||h.message:h};g.disable=function(){g.enable("")};g.enable=function(h){g.save(h);g.names=[];g.skips=[];var p,v=("string"===typeof h?h:"").split(/[\s,]+/),u=v.length;for(p=0;p<u;p++)v[p]&&(h=v[p].replace(/\*/g,".*?"),"-"===h[0]?g.skips.push(new RegExp("^"+h.substr(1)+"$")):g.names.push(new RegExp("^"+
h+"$")));for(p=0;p<g.instances.length;p++)h=g.instances[p],h.enabled=g.enabled(h.namespace)};g.enabled=function(h){if("*"===h[h.length-1])return!0;var p;var v=0;for(p=g.skips.length;v<p;v++)if(g.skips[v].test(h))return!1;v=0;for(p=g.names.length;v<p;v++)if(g.names[v].test(h))return!0;return!1};g.humanize=e(6);g.instances=[];g.names=[];g.skips=[];g.formatters={}},function(n,g){function e(f){f=String(f);if(!(100<f.length)&&(f=/^((?:\d+)?\.?\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|years?|yrs?|y)?$/i.exec(f))){var h=
parseFloat(f[1]);switch((f[2]||"ms").toLowerCase()){case "years":case "year":case "yrs":case "yr":case "y":return h*d;case "days":case "day":case "d":return 864E5*h;case "hours":case "hour":case "hrs":case "hr":case "h":return 36E5*h;case "minutes":case "minute":case "mins":case "min":case "m":return 6E4*h;case "seconds":case "second":case "secs":case "sec":case "s":return 1E3*h;case "milliseconds":case "millisecond":case "msecs":case "msec":case "ms":return h}}}function c(f,h,p){if(!(f<h))return f<
1.5*h?Math.floor(f/h)+" "+p:Math.ceil(f/h)+" "+p+"s"}var d=315576E5;n.exports=function(f,h){h=h||{};var p=typeof f;if("string"===p&&0<f.length)return e(f);if("number"===p&&!1===isNaN(f))return h.long?c(f,864E5,"day")||c(f,36E5,"hour")||c(f,6E4,"minute")||c(f,1E3,"second")||f+" ms":864E5<=f?Math.round(f/864E5)+"d":36E5<=f?Math.round(f/36E5)+"h":6E4<=f?Math.round(f/6E4)+"m":1E3<=f?Math.round(f/1E3)+"s":f+"ms";throw Error("val is not a non-empty string or a valid number. val="+JSON.stringify(f));}},
function(n,g,e){function c(){}function d(a){var b=""+a.type;if(g.BINARY_EVENT===a.type||g.BINARY_ACK===a.type)b+=a.attachments+"-";a.nsp&&"/"!==a.nsp&&(b+=a.nsp+",");null!=a.id&&(b+=a.id);if(null!=a.data){try{var l=JSON.stringify(a.data)}catch(m){l=!1}if(!1!==l)b+=l;else return k}v("encoded %j as %s",a,b);return b}function f(a,b){u.removeBlobs(a,function(l){var m=u.deconstructPacket(l);l=d(m.packet);m=m.buffers;m.unshift(l);b(m)})}function h(){this.reconstructor=null}function p(a){this.reconPack=
a;this.buffers=[]}var v=e(3)("socket.io-parser");n=e(8);var u=e(9),t=e(10),r=e(11);g.protocol=4;g.types="CONNECT DISCONNECT EVENT ACK ERROR BINARY_EVENT BINARY_ACK".split(" ");g.CONNECT=0;g.DISCONNECT=1;g.EVENT=2;g.ACK=3;g.ERROR=4;g.BINARY_EVENT=5;g.BINARY_ACK=6;g.Encoder=c;g.Decoder=h;var k=g.ERROR+'"encode error"';c.prototype.encode=function(a,b){v("encoding packet %j",a);g.BINARY_EVENT===a.type||g.BINARY_ACK===a.type?f(a,b):(a=d(a),b([a]))};n(h.prototype);h.prototype.add=function(a){if("string"===
typeof a){a:{var b=0,l={type:Number(a.charAt(0))};if(null==g.types[l.type])a={type:g.ERROR,data:"parser error: unknown packet type "+l.type};else{if(g.BINARY_EVENT===l.type||g.BINARY_ACK===l.type){for(var m="";"-"!==a.charAt(++b)&&(m+=a.charAt(b),b!=a.length););if(m!=Number(m)||"-"!==a.charAt(b))throw Error("Illegal attachments");l.attachments=Number(m)}if("/"===a.charAt(b+1))for(l.nsp="";++b;){m=a.charAt(b);if(","===m)break;l.nsp+=m;if(b===a.length)break}else l.nsp="/";m=a.charAt(b+1);if(""!==m&&
Number(m)==m){for(l.id="";++b;){m=a.charAt(b);if(null==m||Number(m)!=m){--b;break}l.id+=a.charAt(b);if(b===a.length)break}l.id=Number(l.id)}if(a.charAt(++b)){b=a.substr(b);try{var w=JSON.parse(b)}catch(B){w=!1}if(!1===w||l.type!==g.ERROR&&!t(w)){a={type:g.ERROR,data:"parser error: invalid payload"};break a}else l.data=w}v("decoded %s as %j",a,l);a=l}}g.BINARY_EVENT===a.type||g.BINARY_ACK===a.type?(this.reconstructor=new p(a),0===this.reconstructor.reconPack.attachments&&this.emit("decoded",a)):this.emit("decoded",
a)}else if(r(a)||a.base64)if(this.reconstructor){if(a=this.reconstructor.takeBinaryData(a))this.reconstructor=null,this.emit("decoded",a)}else throw Error("got binary data when not reconstructing a packet");else throw Error("Unknown type: "+a);};h.prototype.destroy=function(){this.reconstructor&&this.reconstructor.finishedReconstruction()};p.prototype.takeBinaryData=function(a){this.buffers.push(a);return this.buffers.length===this.reconPack.attachments?(a=u.reconstructPacket(this.reconPack,this.buffers),
this.finishedReconstruction(),a):null};p.prototype.finishedReconstruction=function(){this.reconPack=null;this.buffers=[]}},function(n,g,e){function c(d){if(d){for(var f in c.prototype)d[f]=c.prototype[f];return d}}n.exports=c;c.prototype.on=c.prototype.addEventListener=function(d,f){this._callbacks=this._callbacks||{};(this._callbacks["$"+d]=this._callbacks["$"+d]||[]).push(f);return this};c.prototype.once=function(d,f){function h(){this.off(d,h);f.apply(this,arguments)}h.fn=f;this.on(d,h);return this};
c.prototype.off=c.prototype.removeListener=c.prototype.removeAllListeners=c.prototype.removeEventListener=function(d,f){this._callbacks=this._callbacks||{};if(0==arguments.length)return this._callbacks={},this;var h=this._callbacks["$"+d];if(!h)return this;if(1==arguments.length)return delete this._callbacks["$"+d],this;for(var p,v=0;v<h.length;v++)if(p=h[v],p===f||p.fn===f){h.splice(v,1);break}return this};c.prototype.emit=function(d){this._callbacks=this._callbacks||{};var f=[].slice.call(arguments,
1),h=this._callbacks["$"+d];if(h){h=h.slice(0);for(var p=0,v=h.length;p<v;++p)h[p].apply(this,f)}return this};c.prototype.listeners=function(d){this._callbacks=this._callbacks||{};return this._callbacks["$"+d]||[]};c.prototype.hasListeners=function(d){return!!this.listeners(d).length}},function(n,g,e){(function(c){function d(r,k){if(!r)return r;if(p(r)){var a={_placeholder:!0,num:k.length};k.push(r);return a}if(h(r)){a=Array(r.length);for(var b=0;b<r.length;b++)a[b]=d(r[b],k);return a}if("object"===
typeof r&&!(r instanceof Date)){a={};for(b in r)a[b]=d(r[b],k);return a}return r}function f(r,k){if(!r)return r;if(r&&r._placeholder)return k[r.num];if(h(r))for(var a=0;a<r.length;a++)r[a]=f(r[a],k);else if("object"===typeof r)for(a in r)r[a]=f(r[a],k);return r}var h=e(10),p=e(11),v=Object.prototype.toString,u="function"===typeof c.Blob||"[object BlobConstructor]"===v.call(c.Blob),t="function"===typeof c.File||"[object FileConstructor]"===v.call(c.File);g.deconstructPacket=function(r){var k=[];r.data=
d(r.data,k);r.attachments=k.length;return{packet:r,buffers:k}};g.reconstructPacket=function(r,k){r.data=f(r.data,k);r.attachments=void 0;return r};g.removeBlobs=function(r,k){function a(m,w,B){if(!m)return m;if(u&&m instanceof Blob||t&&m instanceof File){b++;var q=new FileReader;q.onload=function(){B?B[w]=this.result:l=this.result;--b||k(l)};q.readAsArrayBuffer(m)}else if(h(m))for(q=0;q<m.length;q++)a(m[q],q,m);else if("object"===typeof m&&!p(m))for(q in m)a(m[q],q,m)}var b=0,l=r;a(l);b||k(l)}}).call(g,
function(){return this}())},function(n,g){var e={}.toString;n.exports=Array.isArray||function(c){return"[object Array]"==e.call(c)}},function(n,g){(function(e){n.exports=function(h){return c&&e.Buffer.isBuffer(h)||d&&(h instanceof e.ArrayBuffer||f(h))};var c="function"===typeof e.Buffer&&"function"===typeof e.Buffer.isBuffer,d="function"===typeof e.ArrayBuffer,f=function(){return d&&"function"===typeof e.ArrayBuffer.isView?e.ArrayBuffer.isView:function(h){return h.buffer instanceof e.ArrayBuffer}}()}).call(g,
function(){return this}())},function(n,g,e){function c(b,l){if(!(this instanceof c))return new c(b,l);b&&"object"===("undefined"===typeof b?"undefined":d(b))&&(l=b,b=void 0);l=l||{};l.path=l.path||"/socket.io";this.nsps={};this.subs=[];this.opts=l;this.reconnection(!1!==l.reconnection);this.reconnectionAttempts(l.reconnectionAttempts||Infinity);this.reconnectionDelay(l.reconnectionDelay||1E3);this.reconnectionDelayMax(l.reconnectionDelayMax||5E3);this.randomizationFactor(l.randomizationFactor||.5);
this.backoff=new k({min:this.reconnectionDelay(),max:this.reconnectionDelayMax(),jitter:this.randomizationFactor()});this.timeout(null==l.timeout?2E4:l.timeout);this.readyState="closed";this.uri=b;this.connecting=[];this.lastPing=null;this.encoding=!1;this.packetBuffer=[];var m=l.parser||p;this.encoder=new m.Encoder;this.decoder=new m.Decoder;(this.autoConnect=!1!==l.autoConnect)&&this.open()}var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&
"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b},f=e(13),h=e(37);g=e(8);var p=e(7),v=e(39),u=e(40),t=e(3)("socket.io-client:manager"),r=e(36),k=e(41),a=Object.prototype.hasOwnProperty;n.exports=c;c.prototype.emitAll=function(){this.emit.apply(this,arguments);for(var b in this.nsps)a.call(this.nsps,b)&&this.nsps[b].emit.apply(this.nsps[b],arguments)};c.prototype.updateSocketIds=function(){for(var b in this.nsps)a.call(this.nsps,b)&&(this.nsps[b].id=this.generateId(b))};
c.prototype.generateId=function(b){return("/"===b?"":b+"#")+this.engine.id};g(c.prototype);c.prototype.reconnection=function(b){if(!arguments.length)return this._reconnection;this._reconnection=!!b;return this};c.prototype.reconnectionAttempts=function(b){if(!arguments.length)return this._reconnectionAttempts;this._reconnectionAttempts=b;return this};c.prototype.reconnectionDelay=function(b){if(!arguments.length)return this._reconnectionDelay;this._reconnectionDelay=b;this.backoff&&this.backoff.setMin(b);
return this};c.prototype.randomizationFactor=function(b){if(!arguments.length)return this._randomizationFactor;this._randomizationFactor=b;this.backoff&&this.backoff.setJitter(b);return this};c.prototype.reconnectionDelayMax=function(b){if(!arguments.length)return this._reconnectionDelayMax;this._reconnectionDelayMax=b;this.backoff&&this.backoff.setMax(b);return this};c.prototype.timeout=function(b){if(!arguments.length)return this._timeout;this._timeout=b;return this};c.prototype.maybeReconnectOnOpen=
function(){!this.reconnecting&&this._reconnection&&0===this.backoff.attempts&&this.reconnect()};c.prototype.open=c.prototype.connect=function(b,l){t("readyState %s",this.readyState);if(~this.readyState.indexOf("open"))return this;t("opening %s",this.uri);var m=this.engine=f(this.uri,this.opts),w=this;this.readyState="opening";this.skipReconnect=!1;var B=v(m,"open",function(){w.onopen();b&&b()});l=v(m,"error",function(y){t("connect_error");w.cleanup();w.readyState="closed";w.emitAll("connect_error",
y);if(b){var z=Error("Connection error");z.data=y;b(z)}else w.maybeReconnectOnOpen()});if(!1!==this._timeout){var q=this._timeout;t("connect attempt will timeout after %d",q);var x=setTimeout(function(){t("connect attempt timed out after %d",q);B.destroy();m.close();m.emit("error","timeout");w.emitAll("connect_timeout",q)},q);this.subs.push({destroy:function(){clearTimeout(x)}})}this.subs.push(B);this.subs.push(l);return this};c.prototype.onopen=function(){t("open");this.cleanup();this.readyState=
"open";this.emit("open");var b=this.engine;this.subs.push(v(b,"data",u(this,"ondata")));this.subs.push(v(b,"ping",u(this,"onping")));this.subs.push(v(b,"pong",u(this,"onpong")));this.subs.push(v(b,"error",u(this,"onerror")));this.subs.push(v(b,"close",u(this,"onclose")));this.subs.push(v(this.decoder,"decoded",u(this,"ondecoded")))};c.prototype.onping=function(){this.lastPing=new Date;this.emitAll("ping")};c.prototype.onpong=function(){this.emitAll("pong",new Date-this.lastPing)};c.prototype.ondata=
function(b){this.decoder.add(b)};c.prototype.ondecoded=function(b){this.emit("packet",b)};c.prototype.onerror=function(b){t("error",b);this.emitAll("error",b)};c.prototype.socket=function(b,l){function m(){~r(B.connecting,w)||B.connecting.push(w)}var w=this.nsps[b];if(!w){w=new h(this,b,l);this.nsps[b]=w;var B=this;w.on("connecting",m);w.on("connect",function(){w.id=B.generateId(b)});this.autoConnect&&m()}return w};c.prototype.destroy=function(b){b=r(this.connecting,b);~b&&this.connecting.splice(b,
1);this.connecting.length||this.close()};c.prototype.packet=function(b){t("writing packet %j",b);var l=this;b.query&&0===b.type&&(b.nsp+="?"+b.query);l.encoding?l.packetBuffer.push(b):(l.encoding=!0,this.encoder.encode(b,function(m){for(var w=0;w<m.length;w++)l.engine.write(m[w],b.options);l.encoding=!1;l.processPacketQueue()}))};c.prototype.processPacketQueue=function(){if(0<this.packetBuffer.length&&!this.encoding){var b=this.packetBuffer.shift();this.packet(b)}};c.prototype.cleanup=function(){t("cleanup");
for(var b=this.subs.length,l=0;l<b;l++)this.subs.shift().destroy();this.packetBuffer=[];this.encoding=!1;this.lastPing=null;this.decoder.destroy()};c.prototype.close=c.prototype.disconnect=function(){t("disconnect");this.skipReconnect=!0;this.reconnecting=!1;"opening"===this.readyState&&this.cleanup();this.backoff.reset();this.readyState="closed";this.engine&&this.engine.close()};c.prototype.onclose=function(b){t("onclose");this.cleanup();this.backoff.reset();this.readyState="closed";this.emit("close",
b);this._reconnection&&!this.skipReconnect&&this.reconnect()};c.prototype.reconnect=function(){if(this.reconnecting||this.skipReconnect)return this;var b=this;if(this.backoff.attempts>=this._reconnectionAttempts)t("reconnect failed"),this.backoff.reset(),this.emitAll("reconnect_failed"),this.reconnecting=!1;else{var l=this.backoff.duration();t("will wait %dms before reconnect attempt",l);this.reconnecting=!0;var m=setTimeout(function(){b.skipReconnect||(t("attempting reconnect"),b.emitAll("reconnect_attempt",
b.backoff.attempts),b.emitAll("reconnecting",b.backoff.attempts),b.skipReconnect||b.open(function(w){w?(t("reconnect attempt error"),b.reconnecting=!1,b.reconnect(),b.emitAll("reconnect_error",w.data)):(t("reconnect success"),b.onreconnect())}))},l);this.subs.push({destroy:function(){clearTimeout(m)}})}};c.prototype.onreconnect=function(){var b=this.backoff.attempts;this.reconnecting=!1;this.backoff.reset();this.updateSocketIds();this.emitAll("reconnect",b)}},function(n,g,e){n.exports=e(14);n.exports.parser=
e(21)},function(n,g,e){(function(c){function d(k,a){if(!(this instanceof d))return new d(k,a);a=a||{};k&&"object"===typeof k&&(a=k,k=null);k?(k=t(k),a.hostname=k.host,a.secure="https"===k.protocol||"wss"===k.protocol,a.port=k.port,k.query&&(a.query=k.query)):a.host&&(a.hostname=t(a.host).host);this.secure=null!=a.secure?a.secure:c.location&&"https:"===location.protocol;a.hostname&&!a.port&&(a.port=this.secure?"443":"80");this.agent=a.agent||!1;this.hostname=a.hostname||(c.location?location.hostname:
"localhost");this.port=a.port||(c.location&&location.port?location.port:this.secure?443:80);this.query=a.query||{};"string"===typeof this.query&&(this.query=r.decode(this.query));this.upgrade=!1!==a.upgrade;this.path=(a.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!a.forceJSONP;this.jsonp=!1!==a.jsonp;this.forceBase64=!!a.forceBase64;this.enablesXDR=!!a.enablesXDR;this.timestampParam=a.timestampParam||"t";this.timestampRequests=a.timestampRequests;this.transports=a.transports||["polling",
"websocket"];this.transportOptions=a.transportOptions||{};this.readyState="";this.writeBuffer=[];this.prevBufferLen=0;this.policyPort=a.policyPort||843;this.rememberUpgrade=a.rememberUpgrade||!1;this.binaryType=null;this.onlyBinaryUpgrades=a.onlyBinaryUpgrades;this.perMessageDeflate=!1!==a.perMessageDeflate?a.perMessageDeflate||{}:!1;!0===this.perMessageDeflate&&(this.perMessageDeflate={});this.perMessageDeflate&&null==this.perMessageDeflate.threshold&&(this.perMessageDeflate.threshold=1024);this.pfx=
a.pfx||null;this.key=a.key||null;this.passphrase=a.passphrase||null;this.cert=a.cert||null;this.ca=a.ca||null;this.ciphers=a.ciphers||null;this.rejectUnauthorized=void 0===a.rejectUnauthorized?!0:a.rejectUnauthorized;this.forceNode=!!a.forceNode;k="object"===typeof c&&c;k.global===k&&(a.extraHeaders&&0<Object.keys(a.extraHeaders).length&&(this.extraHeaders=a.extraHeaders),a.localAddress&&(this.localAddress=a.localAddress));this.pingTimeoutTimer=this.pingIntervalTimer=this.pingTimeout=this.pingInterval=
this.upgrades=this.id=null;this.open()}var f=e(15),h=e(8),p=e(3)("engine.io-client:socket"),v=e(36),u=e(21),t=e(2),r=e(30);n.exports=d;d.priorWebsocketSuccess=!1;h(d.prototype);d.protocol=u.protocol;d.Socket=d;d.Transport=e(20);d.transports=e(15);d.parser=e(21);d.prototype.createTransport=function(k){p('creating transport "%s"',k);var a=this.query,b={},l;for(l in a)a.hasOwnProperty(l)&&(b[l]=a[l]);b.EIO=u.protocol;b.transport=k;a=this.transportOptions[k]||{};this.id&&(b.sid=this.id);return new f[k]({query:b,
socket:this,agent:a.agent||this.agent,hostname:a.hostname||this.hostname,port:a.port||this.port,secure:a.secure||this.secure,path:a.path||this.path,forceJSONP:a.forceJSONP||this.forceJSONP,jsonp:a.jsonp||this.jsonp,forceBase64:a.forceBase64||this.forceBase64,enablesXDR:a.enablesXDR||this.enablesXDR,timestampRequests:a.timestampRequests||this.timestampRequests,timestampParam:a.timestampParam||this.timestampParam,policyPort:a.policyPort||this.policyPort,pfx:a.pfx||this.pfx,key:a.key||this.key,passphrase:a.passphrase||
this.passphrase,cert:a.cert||this.cert,ca:a.ca||this.ca,ciphers:a.ciphers||this.ciphers,rejectUnauthorized:a.rejectUnauthorized||this.rejectUnauthorized,perMessageDeflate:a.perMessageDeflate||this.perMessageDeflate,extraHeaders:a.extraHeaders||this.extraHeaders,forceNode:a.forceNode||this.forceNode,localAddress:a.localAddress||this.localAddress,requestTimeout:a.requestTimeout||this.requestTimeout,protocols:a.protocols||void 0})};d.prototype.open=function(){if(this.rememberUpgrade&&d.priorWebsocketSuccess&&
-1!==this.transports.indexOf("websocket"))var k="websocket";else{if(0===this.transports.length){var a=this;setTimeout(function(){a.emit("error","No transports available")},0);return}k=this.transports[0]}this.readyState="opening";try{k=this.createTransport(k)}catch(b){this.transports.shift();this.open();return}k.open();this.setTransport(k)};d.prototype.setTransport=function(k){p("setting transport %s",k.name);var a=this;this.transport&&(p("clearing existing transport %s",this.transport.name),this.transport.removeAllListeners());
this.transport=k;k.on("drain",function(){a.onDrain()}).on("packet",function(b){a.onPacket(b)}).on("error",function(b){a.onError(b)}).on("close",function(){a.onClose("transport close")})};d.prototype.probe=function(k){function a(){if(z.onlyBinaryUpgrades){var A=!this.supportsBinary&&z.transport.supportsBinary;y=y||A}y||(p('probe transport "%s" opened',k),x.send([{type:"ping",data:"probe"}]),x.once("packet",function(C){y||("pong"===C.type&&"probe"===C.data?(p('probe transport "%s" pong',k),z.upgrading=
!0,z.emit("upgrading",x),x&&(d.priorWebsocketSuccess="websocket"===x.name,p('pausing current transport "%s"',z.transport.name),z.transport.pause(function(){y||"closed"===z.readyState||(p("changing transport and sending upgrade packet"),q(),z.setTransport(x),x.send([{type:"upgrade"}]),z.emit("upgrade",x),x=null,z.upgrading=!1,z.flush())}))):(p('probe transport "%s" failed',k),C=Error("probe error"),C.transport=x.name,z.emit("upgradeError",C)))}))}function b(){y||(y=!0,q(),x.close(),x=null)}function l(A){var C=
Error("probe error: "+A);C.transport=x.name;b();p('probe transport "%s" failed because of error: %s',k,A);z.emit("upgradeError",C)}function m(){l("transport closed")}function w(){l("socket closed")}function B(A){x&&A.name!==x.name&&(p('"%s" works - aborting "%s"',A.name,x.name),b())}function q(){x.removeListener("open",a);x.removeListener("error",l);x.removeListener("close",m);z.removeListener("close",w);z.removeListener("upgrading",B)}p('probing transport "%s"',k);var x=this.createTransport(k,{probe:1}),
y=!1,z=this;d.priorWebsocketSuccess=!1;x.once("open",a);x.once("error",l);x.once("close",m);this.once("close",w);this.once("upgrading",B);x.open()};d.prototype.onOpen=function(){p("socket open");this.readyState="open";d.priorWebsocketSuccess="websocket"===this.transport.name;this.emit("open");this.flush();if("open"===this.readyState&&this.upgrade&&this.transport.pause){p("starting upgrade probes");for(var k=0,a=this.upgrades.length;k<a;k++)this.probe(this.upgrades[k])}};d.prototype.onPacket=function(k){if("opening"===
this.readyState||"open"===this.readyState||"closing"===this.readyState)switch(p('socket receive: type "%s", data "%s"',k.type,k.data),this.emit("packet",k),this.emit("heartbeat"),k.type){case "open":this.onHandshake(JSON.parse(k.data));break;case "pong":this.setPing();this.emit("pong");break;case "error":var a=Error("server error");a.code=k.data;this.onError(a);break;case "message":this.emit("data",k.data),this.emit("message",k.data)}else p('packet received with socket readyState "%s"',this.readyState)};
d.prototype.onHandshake=function(k){this.emit("handshake",k);this.id=k.sid;this.transport.query.sid=k.sid;this.upgrades=this.filterUpgrades(k.upgrades);this.pingInterval=k.pingInterval;this.pingTimeout=k.pingTimeout;this.onOpen();"closed"!==this.readyState&&(this.setPing(),this.removeListener("heartbeat",this.onHeartbeat),this.on("heartbeat",this.onHeartbeat))};d.prototype.onHeartbeat=function(k){clearTimeout(this.pingTimeoutTimer);var a=this;a.pingTimeoutTimer=setTimeout(function(){if("closed"!==
a.readyState)a.onClose("ping timeout")},k||a.pingInterval+a.pingTimeout)};d.prototype.setPing=function(){var k=this;clearTimeout(k.pingIntervalTimer);k.pingIntervalTimer=setTimeout(function(){p("writing ping packet - expecting pong within %sms",k.pingTimeout);k.ping();k.onHeartbeat(k.pingTimeout)},k.pingInterval)};d.prototype.ping=function(){var k=this;this.sendPacket("ping",function(){k.emit("ping")})};d.prototype.onDrain=function(){this.writeBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=
0;0===this.writeBuffer.length?this.emit("drain"):this.flush()};d.prototype.flush=function(){"closed"!==this.readyState&&this.transport.writable&&!this.upgrading&&this.writeBuffer.length&&(p("flushing %d packets in socket",this.writeBuffer.length),this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};d.prototype.write=d.prototype.send=function(k,a,b){this.sendPacket("message",k,a,b);return this};d.prototype.sendPacket=function(k,a,b,l){"function"===typeof a&&
(l=a,a=void 0);"function"===typeof b&&(l=b,b=null);if("closing"!==this.readyState&&"closed"!==this.readyState){b=b||{};b.compress=!1!==b.compress;k={type:k,data:a,options:b};this.emit("packetCreate",k);this.writeBuffer.push(k);if(l)this.once("flush",l);this.flush()}};d.prototype.close=function(){function k(){l.onClose("forced close");p("socket closing - telling transport to close");l.transport.close()}function a(){l.removeListener("upgrade",a);l.removeListener("upgradeError",a);k()}function b(){l.once("upgrade",
a);l.once("upgradeError",a)}if("opening"===this.readyState||"open"===this.readyState){this.readyState="closing";var l=this;if(this.writeBuffer.length)this.once("drain",function(){this.upgrading?b():k()});else this.upgrading?b():k()}return this};d.prototype.onError=function(k){p("socket error %j",k);d.priorWebsocketSuccess=!1;this.emit("error",k);this.onClose("transport error",k)};d.prototype.onClose=function(k,a){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)p('socket close with reason: "%s"',
k),clearTimeout(this.pingIntervalTimer),clearTimeout(this.pingTimeoutTimer),this.transport.removeAllListeners("close"),this.transport.close(),this.transport.removeAllListeners(),this.readyState="closed",this.id=null,this.emit("close",k,a),this.writeBuffer=[],this.prevBufferLen=0};d.prototype.filterUpgrades=function(k){for(var a=[],b=0,l=k.length;b<l;b++)~v(this.transports,k[b])&&a.push(k[b]);return a}}).call(g,function(){return this}())},function(n,g,e){(function(c){var d=e(16),f=e(18),h=e(33),p=
e(34);g.polling=function(v){var u=!1,t=!1,r=!1!==v.jsonp;c.location&&(t="https:"===location.protocol,(u=location.port)||(u=t?443:80),u=v.hostname!==location.hostname||u!==v.port,t=v.secure!==t);v.xdomain=u;v.xscheme=t;if("open"in new d(v)&&!v.forceJSONP)return new f(v);if(!r)throw Error("JSONP disabled");return new h(v)};g.websocket=p}).call(g,function(){return this}())},function(n,g,e){(function(c){var d=e(17);n.exports=function(f){var h=f.xdomain,p=f.xscheme;f=f.enablesXDR;try{if("undefined"!==
typeof XMLHttpRequest&&(!h||d))return new XMLHttpRequest}catch(v){}try{if("undefined"!==typeof XDomainRequest&&!p&&f)return new XDomainRequest}catch(v){}if(!h)try{return new (c[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(v){}}}).call(g,function(){return this}())},function(n,g){try{n.exports="undefined"!==typeof XMLHttpRequest&&"withCredentials"in new XMLHttpRequest}catch(e){n.exports=!1}},function(n,g,e){(function(c){function d(){}function f(a){u.call(this,a);this.requestTimeout=
a.requestTimeout;this.extraHeaders=a.extraHeaders;if(c.location){var b="https:"===location.protocol,l=location.port;l||(l=b?443:80);this.xd=a.hostname!==c.location.hostname||l!==a.port;this.xs=a.secure!==b}}function h(a){this.method=a.method||"GET";this.uri=a.uri;this.xd=!!a.xd;this.xs=!!a.xs;this.async=!1!==a.async;this.data=void 0!==a.data?a.data:null;this.agent=a.agent;this.isBinary=a.isBinary;this.supportsBinary=a.supportsBinary;this.enablesXDR=a.enablesXDR;this.requestTimeout=a.requestTimeout;
this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;this.cert=a.cert;this.ca=a.ca;this.ciphers=a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.extraHeaders=a.extraHeaders;this.create()}function p(){for(var a in h.requests)h.requests.hasOwnProperty(a)&&h.requests[a].abort()}var v=e(16),u=e(19),t=e(8),r=e(31),k=e(3)("engine.io-client:polling-xhr");n.exports=f;n.exports.Request=h;r(f,u);f.prototype.supportsBinary=!0;f.prototype.request=function(a){a=a||{};a.uri=this.uri();a.xd=this.xd;
a.xs=this.xs;a.agent=this.agent||!1;a.supportsBinary=this.supportsBinary;a.enablesXDR=this.enablesXDR;a.pfx=this.pfx;a.key=this.key;a.passphrase=this.passphrase;a.cert=this.cert;a.ca=this.ca;a.ciphers=this.ciphers;a.rejectUnauthorized=this.rejectUnauthorized;a.requestTimeout=this.requestTimeout;a.extraHeaders=this.extraHeaders;return new h(a)};f.prototype.doWrite=function(a,b){a=this.request({method:"POST",data:a,isBinary:"string"!==typeof a&&void 0!==a});var l=this;a.on("success",b);a.on("error",
function(m){l.onError("xhr post error",m)});this.sendXhr=a};f.prototype.doPoll=function(){k("xhr poll");var a=this.request(),b=this;a.on("data",function(l){b.onData(l)});a.on("error",function(l){b.onError("xhr poll error",l)});this.pollXhr=a};t(h.prototype);h.prototype.create=function(){var a={agent:this.agent,xdomain:this.xd,xscheme:this.xs,enablesXDR:this.enablesXDR};a.pfx=this.pfx;a.key=this.key;a.passphrase=this.passphrase;a.cert=this.cert;a.ca=this.ca;a.ciphers=this.ciphers;a.rejectUnauthorized=
this.rejectUnauthorized;var b=this.xhr=new v(a),l=this;try{k("xhr open %s: %s",this.method,this.uri);b.open(this.method,this.uri,this.async);try{if(this.extraHeaders){b.setDisableHeaderCheck&&b.setDisableHeaderCheck(!0);for(var m in this.extraHeaders)this.extraHeaders.hasOwnProperty(m)&&b.setRequestHeader(m,this.extraHeaders[m])}}catch(w){}if("POST"===this.method)try{this.isBinary?b.setRequestHeader("Content-type","application/octet-stream"):b.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(w){}try{b.setRequestHeader("Accept",
"*/*")}catch(w){}"withCredentials"in b&&(b.withCredentials=!0);this.requestTimeout&&(b.timeout=this.requestTimeout);this.hasXDR()?(b.onload=function(){l.onLoad()},b.onerror=function(){l.onError(b.responseText)}):b.onreadystatechange=function(){if(2===b.readyState)try{var w=b.getResponseHeader("Content-Type");l.supportsBinary&&"application/octet-stream"===w&&(b.responseType="arraybuffer")}catch(B){}if(4===b.readyState)if(200===b.status||1223===b.status)l.onLoad();else setTimeout(function(){l.onError(b.status)},
0)};k("xhr data %s",this.data);b.send(this.data)}catch(w){setTimeout(function(){l.onError(w)},0);return}c.document&&(this.index=h.requestsCount++,h.requests[this.index]=this)};h.prototype.onSuccess=function(){this.emit("success");this.cleanup()};h.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};h.prototype.onError=function(a){this.emit("error",a);this.cleanup(!0)};h.prototype.cleanup=function(a){if("undefined"!==typeof this.xhr&&null!==this.xhr){this.hasXDR()?this.xhr.onload=this.xhr.onerror=
d:this.xhr.onreadystatechange=d;if(a)try{this.xhr.abort()}catch(b){}c.document&&delete h.requests[this.index];this.xhr=null}};h.prototype.onLoad=function(){try{try{var a=this.xhr.getResponseHeader("Content-Type")}catch(l){}var b="application/octet-stream"===a?this.xhr.response||this.xhr.responseText:this.xhr.responseText}catch(l){this.onError(l)}if(null!=b)this.onData(b)};h.prototype.hasXDR=function(){return"undefined"!==typeof c.XDomainRequest&&!this.xs&&this.enablesXDR};h.prototype.abort=function(){this.cleanup()};
h.requestsCount=0;h.requests={};c.document&&(c.attachEvent?c.attachEvent("onunload",p):c.addEventListener&&c.addEventListener("beforeunload",p,!1))}).call(g,function(){return this}())},function(n,g,e){function c(t){var r=t&&t.forceBase64;if(!u||r)this.supportsBinary=!1;d.call(this,t)}var d=e(20),f=e(30),h=e(21);g=e(31);var p=e(32),v=e(3)("engine.io-client:polling");n.exports=c;var u=null!=(new (e(16))({xdomain:!1})).responseType;g(c,d);c.prototype.name="polling";c.prototype.doOpen=function(){this.poll()};
c.prototype.pause=function(t){function r(){v("paused");k.readyState="paused";t()}var k=this;this.readyState="pausing";if(this.polling||!this.writable){var a=0;this.polling&&(v("we are currently polling - waiting to pause"),a++,this.once("pollComplete",function(){v("pre-pause polling complete");--a||r()}));this.writable||(v("we are currently writing - waiting to pause"),a++,this.once("drain",function(){v("pre-pause writing complete");--a||r()}))}else r()};c.prototype.poll=function(){v("polling");this.polling=
!0;this.doPoll();this.emit("poll")};c.prototype.onData=function(t){var r=this;v("polling got data %s",t);h.decodePayload(t,this.socket.binaryType,function(k,a,b){if("opening"===r.readyState)r.onOpen();if("close"===k.type)return r.onClose(),!1;r.onPacket(k)});"closed"!==this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"===this.readyState?this.poll():v('ignoring poll - transport state "%s"',this.readyState))};c.prototype.doClose=function(){function t(){v("writing close packet");r.write([{type:"close"}])}
var r=this;"open"===this.readyState?(v("transport open - closing"),t()):(v("transport not open - deferring close"),this.once("open",t))};c.prototype.write=function(t){var r=this;this.writable=!1;var k=function(){r.writable=!0;r.emit("drain")};h.encodePayload(t,this.supportsBinary,function(a){r.doWrite(a,k)})};c.prototype.uri=function(){var t=this.query||{},r=this.secure?"https":"http",k="";!1!==this.timestampRequests&&(t[this.timestampParam]=p());this.supportsBinary||t.sid||(t.b64=1);t=f.encode(t);
this.port&&("https"===r&&443!==Number(this.port)||"http"===r&&80!==Number(this.port))&&(k=":"+this.port);t.length&&(t="?"+t);var a=-1!==this.hostname.indexOf(":");return r+"://"+(a?"["+this.hostname+"]":this.hostname)+k+this.path+t}},function(n,g,e){function c(f){this.path=f.path;this.hostname=f.hostname;this.port=f.port;this.secure=f.secure;this.query=f.query;this.timestampParam=f.timestampParam;this.timestampRequests=f.timestampRequests;this.readyState="";this.agent=f.agent||!1;this.socket=f.socket;
this.enablesXDR=f.enablesXDR;this.pfx=f.pfx;this.key=f.key;this.passphrase=f.passphrase;this.cert=f.cert;this.ca=f.ca;this.ciphers=f.ciphers;this.rejectUnauthorized=f.rejectUnauthorized;this.forceNode=f.forceNode;this.extraHeaders=f.extraHeaders;this.localAddress=f.localAddress}var d=e(21);g=e(8);n.exports=c;g(c.prototype);c.prototype.onError=function(f,h){f=Error(f);f.type="TransportError";f.description=h;this.emit("error",f);return this};c.prototype.open=function(){if("closed"===this.readyState||
""===this.readyState)this.readyState="opening",this.doOpen();return this};c.prototype.close=function(){if("opening"===this.readyState||"open"===this.readyState)this.doClose(),this.onClose();return this};c.prototype.send=function(f){if("open"===this.readyState)this.write(f);else throw Error("Transport not open");};c.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};c.prototype.onData=function(f){f=d.decodePacket(f,this.socket.binaryType);this.onPacket(f)};c.prototype.onPacket=
function(f){this.emit("packet",f)};c.prototype.onClose=function(){this.readyState="closed";this.emit("close")}},function(n,g,e){(function(c){function d(q,x,y){if(!x)return g.encodeBase64Packet(q,y);var z=new FileReader;z.onload=function(){q.data=z.result;g.encodePacket(q,x,!0,y)};return z.readAsArrayBuffer(q.data)}function f(q,x,y){var z=Array(q.length);y=u(q.length,y);for(var A=function(D,E,F){x(E,function(G,H){z[D]=H;F(G,z)})},C=0;C<q.length;C++)A(C,q[C],y)}var h=e(22),p=e(23),v=e(24),u=e(25),t=
e(26),r;c&&c.ArrayBuffer&&(r=e(28));var k="undefined"!==typeof navigator&&/Android/i.test(navigator.userAgent),a="undefined"!==typeof navigator&&/PhantomJS/i.test(navigator.userAgent),b=k||a;g.protocol=3;var l=g.packets={open:0,close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},m=h(l),w={type:"error",data:"parser error"},B=e(29);g.encodePacket=function(q,x,y,z){"function"===typeof x&&(z=x,x=!1);"function"===typeof y&&(z=y,y=null);var A=void 0===q.data?void 0:q.data.buffer||q.data;if(c.ArrayBuffer&&
A instanceof ArrayBuffer){if(x){y=q.data;x=new Uint8Array(y);y=new Uint8Array(1+y.byteLength);y[0]=l[q.type];for(q=0;q<x.length;q++)y[q+1]=x[q];q=z(y.buffer)}else q=g.encodeBase64Packet(q,z);return q}if(B&&A instanceof c.Blob)return x?b?q=d(q,x,z):(x=new Uint8Array(1),x[0]=l[q.type],q=new B([x.buffer,q.data]),q=z(q)):q=g.encodeBase64Packet(q,z),q;if(A&&A.base64)return z("b"+g.packets[q.type]+q.data.data);x=l[q.type];void 0!==q.data&&(x+=y?t.encode(String(q.data),{strict:!1}):String(q.data));return z(""+
x)};g.encodeBase64Packet=function(q,x){var y="b"+g.packets[q.type];if(B&&q.data instanceof c.Blob){var z=new FileReader;z.onload=function(){var D=z.result.split(",")[1];x(y+D)};return z.readAsDataURL(q.data)}try{var A=String.fromCharCode.apply(null,new Uint8Array(q.data))}catch(D){q=new Uint8Array(q.data);A=Array(q.length);for(var C=0;C<q.length;C++)A[C]=q[C];A=String.fromCharCode.apply(null,A)}y+=c.btoa(A);return x(y)};g.decodePacket=function(q,x,y){if(void 0===q)return w;if("string"===typeof q){if("b"===
q.charAt(0))return g.decodeBase64Packet(q.substr(1),x);if(y){a:{x=q;try{x=t.decode(x,{strict:!1})}catch(z){q=!1;break a}q=x}if(!1===q)return w}y=q.charAt(0);return Number(y)==y&&m[y]?1<q.length?{type:m[y],data:q.substring(1)}:{type:m[y]}:w}y=(new Uint8Array(q))[0];q=v(q,1);B&&"blob"===x&&(q=new B([q]));return{type:m[y],data:q}};g.decodeBase64Packet=function(q,x){var y=m[q.charAt(0)];if(!r)return{type:y,data:{base64:!0,data:q.substr(1)}};q=r.decode(q.substr(1));"blob"===x&&B&&(q=new B([q]));return{type:y,
data:q}};g.encodePayload=function(q,x,y){"function"===typeof x&&(y=x,x=null);var z=p(q);if(x&&z)return B&&!b?g.encodePayloadAsBlob(q,y):g.encodePayloadAsArrayBuffer(q,y);if(!q.length)return y("0:");f(q,function(A,C){g.encodePacket(A,z?x:!1,!1,function(D){C(null,D.length+":"+D)})},function(A,C){return y(C.join(""))})};g.decodePayload=function(q,x,y){if("string"!==typeof q)return g.decodePayloadAsBinary(q,x,y);"function"===typeof x&&(y=x,x=null);if(""===q)return y(w,0,1);var z="";for(var A,C,D=0,E=
q.length;D<E;D++)if(C=q.charAt(D),":"!==C)z+=C;else{if(""===z||z!=(A=Number(z)))return y(w,0,1);C=q.substr(D+1,A);if(z!=C.length)return y(w,0,1);if(C.length){z=g.decodePacket(C,x,!1);if(w.type===z.type&&w.data===z.data)return y(w,0,1);if(!1===y(z,D+A,E))return}D+=A;z=""}if(""!==z)return y(w,0,1)};g.encodePayloadAsArrayBuffer=function(q,x){if(!q.length)return x(new ArrayBuffer(0));f(q,function(y,z){g.encodePacket(y,!0,!0,function(A){return z(null,A)})},function(y,z){y=z.reduce(function(D,E){E="string"===
typeof E?E.length:E.byteLength;return D+E.toString().length+E+2},0);var A=new Uint8Array(y),C=0;z.forEach(function(D){var E="string"===typeof D,F=D;if(E){F=new Uint8Array(D.length);for(var G=0;G<D.length;G++)F[G]=D.charCodeAt(G);F=F.buffer}E?A[C++]=0:A[C++]=1;D=F.byteLength.toString();for(G=0;G<D.length;G++)A[C++]=parseInt(D[G]);A[C++]=255;F=new Uint8Array(F);for(G=0;G<F.length;G++)A[C++]=F[G]});return x(A.buffer)})};g.encodePayloadAsBlob=function(q,x){f(q,function(y,z){g.encodePacket(y,!0,!0,function(A){var C=
new Uint8Array(1);C[0]=1;if("string"===typeof A){for(var D=new Uint8Array(A.length),E=0;E<A.length;E++)D[E]=A.charCodeAt(E);A=D.buffer;C[0]=0}D=(A instanceof ArrayBuffer?A.byteLength:A.size).toString();var F=new Uint8Array(D.length+1);for(E=0;E<D.length;E++)F[E]=parseInt(D[E]);F[D.length]=255;B&&(A=new B([C.buffer,F.buffer,A]),z(null,A))})},function(y,z){return x(new B(z))})};g.decodePayloadAsBinary=function(q,x,y){"function"===typeof x&&(y=x,x=null);for(var z=[];0<q.byteLength;){for(var A=new Uint8Array(q),
C=0===A[0],D="",E=1;255!==A[E];E++){if(310<D.length)return y(w,0,1);D+=A[E]}q=v(q,2+D.length);D=parseInt(D);A=v(q,0,D);if(C)try{A=String.fromCharCode.apply(null,new Uint8Array(A))}catch(G){for(C=new Uint8Array(A),A="",E=0;E<C.length;E++)A+=String.fromCharCode(C[E])}z.push(A);q=v(q,D)}var F=z.length;z.forEach(function(G,H){y(g.decodePacket(G,x,!0),H,F)})}}).call(g,function(){return this}())},function(n,g){n.exports=Object.keys||function(e){var c=[],d=Object.prototype.hasOwnProperty,f;for(f in e)d.call(e,
f)&&c.push(f);return c}},function(n,g,e){(function(c){function d(u){if(!u||"object"!==typeof u)return!1;if(f(u)){for(var t=0,r=u.length;t<r;t++)if(d(u[t]))return!0;return!1}if("function"===typeof c.Buffer&&c.Buffer.isBuffer&&c.Buffer.isBuffer(u)||"function"===typeof c.ArrayBuffer&&u instanceof ArrayBuffer||p&&u instanceof Blob||v&&u instanceof File)return!0;if(u.toJSON&&"function"===typeof u.toJSON&&1===arguments.length)return d(u.toJSON(),!0);for(t in u)if(Object.prototype.hasOwnProperty.call(u,
t)&&d(u[t]))return!0;return!1}var f=e(10),h=Object.prototype.toString,p="function"===typeof c.Blob||"[object BlobConstructor]"===h.call(c.Blob),v="function"===typeof c.File||"[object FileConstructor]"===h.call(c.File);n.exports=d}).call(g,function(){return this}())},function(n,g){n.exports=function(e,c,d){var f=e.byteLength;c=c||0;d=d||f;if(e.slice)return e.slice(c,d);0>c&&(c+=f);0>d&&(d+=f);d>f&&(d=f);if(c>=f||c>=d||0===f)return new ArrayBuffer(0);e=new Uint8Array(e);f=new Uint8Array(d-c);for(var h=
0;c<d;c++,h++)f[h]=e[c];return f.buffer}},function(n,g){function e(){}n.exports=function(c,d,f){function h(v,u){if(0>=h.count)throw Error("after called too many times");--h.count;v?(p=!0,d(v),d=f):0!==h.count||p||d(null,u)}var p=!1;f=f||e;h.count=c;return 0===c?d():h}},function(n,g,e){var c;(function(d,f){(function(h){function p(l){for(var m=[],w=0,B=l.length,q,x;w<B;)q=l.charCodeAt(w++),55296<=q&&56319>=q&&w<B?(x=l.charCodeAt(w++),56320==(x&64512)?m.push(((q&1023)<<10)+(x&1023)+65536):(m.push(q),
w--)):m.push(q);return m}function v(l,m){if(55296<=l&&57343>=l){if(m)throw Error("Lone surrogate U+"+l.toString(16).toUpperCase()+" is not a scalar value");return!1}return!0}function u(){if(b>=a)throw Error("Invalid byte index");var l=k[b]&255;b++;if(128==(l&192))return l&63;throw Error("Invalid continuation byte");}function t(l){if(b>a)throw Error("Invalid byte index");if(b==a)return!1;var m=k[b]&255;b++;if(0==(m&128))return m;if(192==(m&224)){var w=u();m=(m&31)<<6|w;if(128<=m)return m;throw Error("Invalid continuation byte");
}if(224==(m&240)){w=u();var B=u();m=(m&15)<<12|w<<6|B;if(2048<=m)return v(m,l)?m:65533;throw Error("Invalid continuation byte");}if(240==(m&248)&&(w=u(),B=u(),l=u(),m=(m&7)<<18|w<<12|B<<6|l,65536<=m&&1114111>=m))return m;throw Error("Invalid UTF-8 detected");}var r=String.fromCharCode,k,a,b;!(c={version:"2.1.2",encode:function(l,m){m=m||{};m=!1!==m.strict;l=p(l);for(var w=l.length,B=-1,q,x="";++B<w;){q=l[B];var y=m;if(0==(q&4294967168))q=r(q);else{var z="";0==(q&4294965248)?z=r(q>>6&31|192):0==(q&
4294901760)?(v(q,y)||(q=65533),z=r(q>>12&15|224),z+=r(q>>6&63|128)):0==(q&4292870144)&&(z=r(q>>18&7|240),z+=r(q>>12&63|128),z+=r(q>>6&63|128));q=z+=r(q&63|128)}x+=q}return x},decode:function(l,m){m=m||{};m=!1!==m.strict;k=p(l);a=k.length;b=0;l=[];for(var w;!1!==(w=t(m));)l.push(w);m=l.length;w=-1;for(var B,q="";++w<m;)B=l[w],65535<B&&(B-=65536,q+=r(B>>>10&1023|55296),B=56320|B&1023),q+=r(B);return q}},void 0!==c&&(d.exports=c))})(this)}).call(g,e(27)(n),function(){return this}())},function(n,g){n.exports=
function(e){e.webpackPolyfill||(e.deprecate=function(){},e.paths=[],e.children=[],e.webpackPolyfill=1);return e}},function(n,g){(function(){for(var e=new Uint8Array(256),c=0;64>c;c++)e["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(c)]=c;g.encode=function(d){d=new Uint8Array(d);var f,h=d.length,p="";for(f=0;f<h;f+=3)p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d[f]>>2],p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(d[f]&
3)<<4|d[f+1]>>4],p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(d[f+1]&15)<<2|d[f+2]>>6],p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[d[f+2]&63];2===h%3?p=p.substring(0,p.length-1)+"=":1===h%3&&(p=p.substring(0,p.length-2)+"==");return p};g.decode=function(d){var f=.75*d.length,h=d.length,p=0;"="===d[d.length-1]&&(f--,"="===d[d.length-2]&&f--);var v=new ArrayBuffer(f),u=new Uint8Array(v);for(f=0;f<h;f+=4){var t=e[d.charCodeAt(f)];var r=e[d.charCodeAt(f+
1)];var k=e[d.charCodeAt(f+2)];var a=e[d.charCodeAt(f+3)];u[p++]=t<<2|r>>4;u[p++]=(r&15)<<4|k>>2;u[p++]=(k&3)<<6|a&63}return v}})()},function(n,g){(function(e){function c(t){for(var r=0;r<t.length;r++){var k=t[r];if(k.buffer instanceof ArrayBuffer){var a=k.buffer;if(k.byteLength!==a.byteLength){var b=new Uint8Array(k.byteLength);b.set(new Uint8Array(a,k.byteOffset,k.byteLength));a=b.buffer}t[r]=a}}}function d(t,r){r=r||{};var k=new h;c(t);for(var a=0;a<t.length;a++)k.append(t[a]);return r.type?k.getBlob(r.type):
k.getBlob()}function f(t,r){c(t);return new Blob(t,r||{})}var h=e.BlobBuilder||e.WebKitBlobBuilder||e.MSBlobBuilder||e.MozBlobBuilder;try{var p=2===(new Blob(["hi"])).size}catch(t){p=!1}var v;if(v=p)try{v=2===(new Blob([new Uint8Array([1,2])])).size}catch(t){v=!1}var u=h&&h.prototype.append&&h.prototype.getBlob;e=p?v?e.Blob:f:u?d:void 0;n.exports=e}).call(g,function(){return this}())},function(n,g){g.encode=function(e){var c="",d;for(d in e)e.hasOwnProperty(d)&&(c.length&&(c+="&"),c+=encodeURIComponent(d)+
"="+encodeURIComponent(e[d]));return c};g.decode=function(e){var c={};e=e.split("&");for(var d=0,f=e.length;d<f;d++){var h=e[d].split("=");c[decodeURIComponent(h[0])]=decodeURIComponent(h[1])}return c}},function(n,g){n.exports=function(e,c){var d=function(){};d.prototype=c.prototype;e.prototype=new d;e.prototype.constructor=e}},function(n,g){function e(u){var t="";do t=d[u%64]+t,u=Math.floor(u/64);while(0<u);return t}function c(){var u=e(+new Date);return u!==v?(h=0,v=u):u+"."+e(h++)}for(var d="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_".split(""),
f={},h=0,p=0,v;64>p;p++)f[d[p]]=p;c.encode=e;c.decode=function(u){var t=0;for(p=0;p<u.length;p++)t=64*t+f[u.charAt(p)];return t};n.exports=c},function(n,g,e){(function(c){function d(){}function f(r){h.call(this,r);this.query=this.query||{};t||(c.___eio||(c.___eio=[]),t=c.___eio);this.index=t.length;var k=this;t.push(function(a){k.onData(a)});this.query.j=this.index;c.document&&c.addEventListener&&c.addEventListener("beforeunload",function(){k.script&&(k.script.onerror=d)},!1)}var h=e(19),p=e(31);
n.exports=f;var v=/\n/g,u=/\\n/g,t;p(f,h);f.prototype.supportsBinary=!1;f.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&(this.form.parentNode.removeChild(this.form),this.iframe=this.form=null);h.prototype.doClose.call(this)};f.prototype.doPoll=function(){var r=this,k=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);k.async=!0;k.src=this.uri();k.onerror=function(b){r.onError("jsonp poll error",
b)};var a=document.getElementsByTagName("script")[0];a?a.parentNode.insertBefore(k,a):(document.head||document.body).appendChild(k);this.script=k;"undefined"!==typeof navigator&&/gecko/i.test(navigator.userAgent)&&setTimeout(function(){var b=document.createElement("iframe");document.body.appendChild(b);document.body.removeChild(b)},100)};f.prototype.doWrite=function(r,k){function a(){b();k()}function b(){if(l.iframe)try{l.form.removeChild(l.iframe)}catch(x){l.onError("jsonp polling iframe removal error",
x)}try{q=document.createElement('<iframe src="javascript:0" name="'+l.iframeId+'">')}catch(x){q=document.createElement("iframe"),q.name=l.iframeId,q.src="javascript:0"}q.id=l.iframeId;l.form.appendChild(q);l.iframe=q}var l=this;if(!this.form){var m=document.createElement("form"),w=document.createElement("textarea"),B=this.iframeId="eio_iframe_"+this.index,q;m.className="socketio";m.style.position="absolute";m.style.top="-1000px";m.style.left="-1000px";m.target=B;m.method="POST";m.setAttribute("accept-charset",
"utf-8");w.name="d";m.appendChild(w);document.body.appendChild(m);this.form=m;this.area=w}this.form.action=this.uri();b();r=r.replace(u,"\\\n");this.area.value=r.replace(v,"\\n");try{this.form.submit()}catch(x){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"===l.iframe.readyState&&a()}:this.iframe.onload=a}}).call(g,function(){return this}())},function(n,g,e){(function(c){function d(b){b&&b.forceBase64&&(this.supportsBinary=!1);this.perMessageDeflate=b.perMessageDeflate;
this.usingBrowserWebSocket=r&&!b.forceNode;this.protocols=b.protocols;this.usingBrowserWebSocket||(a=k);f.call(this,b)}var f=e(20),h=e(21),p=e(30),v=e(31),u=e(32),t=e(3)("engine.io-client:websocket"),r=c.WebSocket||c.MozWebSocket;if("undefined"===typeof window)try{var k=e(35)}catch(b){}var a=r;a||"undefined"!==typeof window||(a=k);n.exports=d;v(d,f);d.prototype.name="websocket";d.prototype.supportsBinary=!0;d.prototype.doOpen=function(){if(this.check()){var b=this.uri(),l=this.protocols,m={agent:this.agent,
perMessageDeflate:this.perMessageDeflate};m.pfx=this.pfx;m.key=this.key;m.passphrase=this.passphrase;m.cert=this.cert;m.ca=this.ca;m.ciphers=this.ciphers;m.rejectUnauthorized=this.rejectUnauthorized;this.extraHeaders&&(m.headers=this.extraHeaders);this.localAddress&&(m.localAddress=this.localAddress);try{this.ws=this.usingBrowserWebSocket?l?new a(b,l):new a(b):new a(b,l,m)}catch(w){return this.emit("error",w)}void 0===this.ws.binaryType&&(this.supportsBinary=!1);this.ws.supports&&this.ws.supports.binary?
(this.supportsBinary=!0,this.ws.binaryType="nodebuffer"):this.ws.binaryType="arraybuffer";this.addEventListeners()}};d.prototype.addEventListeners=function(){var b=this;this.ws.onopen=function(){b.onOpen()};this.ws.onclose=function(){b.onClose()};this.ws.onmessage=function(l){b.onData(l.data)};this.ws.onerror=function(l){b.onError("websocket error",l)}};d.prototype.write=function(b){function l(){m.emit("flush");setTimeout(function(){m.writable=!0;m.emit("drain")},0)}var m=this;this.writable=!1;for(var w=
b.length,B=0,q=w;B<q;B++)(function(x){h.encodePacket(x,m.supportsBinary,function(y){if(!m.usingBrowserWebSocket){var z={};x.options&&(z.compress=x.options.compress);m.perMessageDeflate&&("string"===typeof y?c.Buffer.byteLength(y):y.length)<m.perMessageDeflate.threshold&&(z.compress=!1)}try{m.usingBrowserWebSocket?m.ws.send(y):m.ws.send(y,z)}catch(A){t("websocket closed before onclose event")}--w||l()})})(b[B])};d.prototype.onClose=function(){f.prototype.onClose.call(this)};d.prototype.doClose=function(){"undefined"!==
typeof this.ws&&this.ws.close()};d.prototype.uri=function(){var b=this.query||{},l=this.secure?"wss":"ws",m="";this.port&&("wss"===l&&443!==Number(this.port)||"ws"===l&&80!==Number(this.port))&&(m=":"+this.port);this.timestampRequests&&(b[this.timestampParam]=u());this.supportsBinary||(b.b64=1);b=p.encode(b);b.length&&(b="?"+b);var w=-1!==this.hostname.indexOf(":");return l+"://"+(w?"["+this.hostname+"]":this.hostname)+m+this.path+b};d.prototype.check=function(){return!!a&&!("__initialize"in a&&this.name===
d.prototype.name)}}).call(g,function(){return this}())},function(n,g){},function(n,g){var e=[].indexOf;n.exports=function(c,d){if(e)return c.indexOf(d);for(var f=0;f<c.length;++f)if(c[f]===d)return f;return-1}},function(n,g,e){function c(b,l,m){this.io=b;this.nsp=l;this.json=this;this.ids=0;this.acks={};this.receiveBuffer=[];this.sendBuffer=[];this.connected=!1;this.disconnected=!0;this.flags={};m&&m.query&&(this.query=m.query);this.io.autoConnect&&this.open()}var d="function"===typeof Symbol&&"symbol"===
typeof Symbol.iterator?function(b){return typeof b}:function(b){return b&&"function"===typeof Symbol&&b.constructor===Symbol&&b!==Symbol.prototype?"symbol":typeof b},f=e(7);g=e(8);var h=e(38),p=e(39),v=e(40),u=e(3)("socket.io-client:socket"),t=e(30),r=e(23);n.exports=c;var k={connect:1,connect_error:1,connect_timeout:1,connecting:1,disconnect:1,error:1,reconnect:1,reconnect_attempt:1,reconnect_failed:1,reconnect_error:1,reconnecting:1,ping:1,pong:1},a=g.prototype.emit;g(c.prototype);c.prototype.subEvents=
function(){if(!this.subs){var b=this.io;this.subs=[p(b,"open",v(this,"onopen")),p(b,"packet",v(this,"onpacket")),p(b,"close",v(this,"onclose"))]}};c.prototype.open=c.prototype.connect=function(){if(this.connected)return this;this.subEvents();this.io.open();if("open"===this.io.readyState)this.onopen();this.emit("connecting");return this};c.prototype.send=function(){var b=h(arguments);b.unshift("message");this.emit.apply(this,b);return this};c.prototype.emit=function(b){if(k.hasOwnProperty(b))return a.apply(this,
arguments),this;var l=h(arguments),m={type:(void 0!==this.flags.binary?this.flags.binary:r(l))?f.BINARY_EVENT:f.EVENT,data:l,options:{}};m.options.compress=!this.flags||!1!==this.flags.compress;"function"===typeof l[l.length-1]&&(u("emitting packet with ack id %d",this.ids),this.acks[this.ids]=l.pop(),m.id=this.ids++);this.connected?this.packet(m):this.sendBuffer.push(m);this.flags={};return this};c.prototype.packet=function(b){b.nsp=this.nsp;this.io.packet(b)};c.prototype.onopen=function(){u("transport is open - connecting");
if("/"!==this.nsp)if(this.query){var b="object"===d(this.query)?t.encode(this.query):this.query;u("sending connect packet with query %s",b);this.packet({type:f.CONNECT,query:b})}else this.packet({type:f.CONNECT})};c.prototype.onclose=function(b){u("close (%s)",b);this.connected=!1;this.disconnected=!0;delete this.id;this.emit("disconnect",b)};c.prototype.onpacket=function(b){var l=b.type===f.ERROR&&"/"===b.nsp;if(b.nsp===this.nsp||l)switch(b.type){case f.CONNECT:this.onconnect();break;case f.EVENT:this.onevent(b);
break;case f.BINARY_EVENT:this.onevent(b);break;case f.ACK:this.onack(b);break;case f.BINARY_ACK:this.onack(b);break;case f.DISCONNECT:this.ondisconnect();break;case f.ERROR:this.emit("error",b.data)}};c.prototype.onevent=function(b){var l=b.data||[];u("emitting event %j",l);null!=b.id&&(u("attaching ack callback to event"),l.push(this.ack(b.id)));this.connected?a.apply(this,l):this.receiveBuffer.push(l)};c.prototype.ack=function(b){var l=this,m=!1;return function(){if(!m){m=!0;var w=h(arguments);
u("sending ack %j",w);l.packet({type:r(w)?f.BINARY_ACK:f.ACK,id:b,data:w})}}};c.prototype.onack=function(b){var l=this.acks[b.id];"function"===typeof l?(u("calling ack %s with %j",b.id,b.data),l.apply(this,b.data),delete this.acks[b.id]):u("bad ack %s",b.id)};c.prototype.onconnect=function(){this.connected=!0;this.disconnected=!1;this.emit("connect");this.emitBuffered()};c.prototype.emitBuffered=function(){var b;for(b=0;b<this.receiveBuffer.length;b++)a.apply(this,this.receiveBuffer[b]);this.receiveBuffer=
[];for(b=0;b<this.sendBuffer.length;b++)this.packet(this.sendBuffer[b]);this.sendBuffer=[]};c.prototype.ondisconnect=function(){u("server disconnect (%s)",this.nsp);this.destroy();this.onclose("io server disconnect")};c.prototype.destroy=function(){if(this.subs){for(var b=0;b<this.subs.length;b++)this.subs[b].destroy();this.subs=null}this.io.destroy(this)};c.prototype.close=c.prototype.disconnect=function(){this.connected&&(u("performing disconnect (%s)",this.nsp),this.packet({type:f.DISCONNECT}));
this.destroy();if(this.connected)this.onclose("io client disconnect");return this};c.prototype.compress=function(b){this.flags.compress=b;return this};c.prototype.binary=function(b){this.flags.binary=b;return this}},function(n,g){n.exports=function(e,c){for(var d=[],f=(c=c||0)||0;f<e.length;f++)d[f-c]=e[f];return d}},function(n,g){n.exports=function(e,c,d){e.on(c,d);return{destroy:function(){e.removeListener(c,d)}}}},function(n,g){var e=[].slice;n.exports=function(c,d){"string"==typeof d&&(d=c[d]);
if("function"!=typeof d)throw Error("bind() requires a function");var f=e.call(arguments,2);return function(){return d.apply(c,f.concat(e.call(arguments)))}}},function(n,g){function e(c){c=c||{};this.ms=c.min||100;this.max=c.max||1E4;this.factor=c.factor||2;this.jitter=0<c.jitter&&1>=c.jitter?c.jitter:0;this.attempts=0}n.exports=e;e.prototype.duration=function(){var c=this.ms*Math.pow(this.factor,this.attempts++);if(this.jitter){var d=Math.random(),f=Math.floor(d*this.jitter*c);c=0==(Math.floor(10*
d)&1)?c-f:c+f}return Math.min(c,this.max)|0};e.prototype.reset=function(){this.attempts=0};e.prototype.setMin=function(c){this.ms=c};e.prototype.setMax=function(c){this.max=c};e.prototype.setJitter=function(c){this.jitter=c}}])});var module$exports$google3$research$colab$oldui$static$js$ga={};(function(n,g,e,c,d,f,h){n.GoogleAnalyticsObject=d;n[d]=n[d]||function(){(n[d].q=n[d].q||[]).push(arguments)};n[d].l=1*new Date;f=g.createElement(e);h=g.getElementsByTagName(e)[0];f.async=1;f.src=c;h.parentNode.insertBefore(f,h)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");
