/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=function(c){var a=0;return function(){return a<c.length?{done:!1,value:c[a++]}:{done:!0}}},r="function"==typeof Object.defineProperties?Object.defineProperty:function(c,a,f){if(c==Array.prototype||c==Object.prototype)return c;c[a]=f.value;return c},t=function(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<c.length;++a){var f=c[a];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");
},u=t(this),v=function(c,a){if(a)a:{var f=u;c=c.split(".");for(var h=0;h<c.length-1;h++){var e=c[h];if(!(e in f))break a;f=f[e]}c=c[c.length-1];h=f[c];a=a(h);a!=h&&null!=a&&r(f,c,{configurable:!0,writable:!0,value:a})}},w=function(c){var a="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return a?a.call(c):{next:n(c)}};
v("Promise",function(c){function a(){this.g=null}function f(b){return b instanceof e?b:new e(function(d){d(b)})}if(c)return c;a.prototype.h=function(b){if(null==this.g){this.g=[];var d=this;this.i(function(){d.l()})}this.g.push(b)};var h=u.setTimeout;a.prototype.i=function(b){h(b,0)};a.prototype.l=function(){for(;this.g&&this.g.length;){var b=this.g;this.g=[];for(var d=0;d<b.length;++d){var g=b[d];b[d]=null;try{g()}catch(k){this.j(k)}}}this.g=null};a.prototype.j=function(b){this.i(function(){throw b;
})};var e=function(b){this.h=0;this.i=void 0;this.g=[];this.s=!1;var d=this.j();try{b(d.resolve,d.reject)}catch(g){d.reject(g)}};e.prototype.j=function(){function b(k){return function(l){g||(g=!0,k.call(d,l))}}var d=this,g=!1;return{resolve:b(this.A),reject:b(this.l)}};e.prototype.A=function(b){if(b===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof e)this.C(b);else{a:switch(typeof b){case "object":var d=null!=b;break a;case "function":d=!0;break a;default:d=!1}d?
this.v(b):this.o(b)}};e.prototype.v=function(b){var d=void 0;try{d=b.then}catch(g){this.l(g);return}"function"==typeof d?this.D(d,b):this.o(b)};e.prototype.l=function(b){this.u(2,b)};e.prototype.o=function(b){this.u(1,b)};e.prototype.u=function(b,d){if(0!=this.h)throw Error("Cannot settle("+b+", "+d+"): Promise already settled in state"+this.h);this.h=b;this.i=d;2===this.h&&this.B();this.F()};e.prototype.B=function(){var b=this;h(function(){if(b.G()){var d=u.console;"undefined"!==typeof d&&d.error(b.i)}},
1)};e.prototype.G=function(){if(this.s)return!1;var b=u.CustomEvent,d=u.Event,g=u.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof b?b=new b("unhandledrejection",{cancelable:!0}):"function"===typeof d?b=new d("unhandledrejection",{cancelable:!0}):(b=u.document.createEvent("CustomEvent"),b.initCustomEvent("unhandledrejection",!1,!0,b));b.promise=this;b.reason=this.i;return g(b)};e.prototype.F=function(){if(null!=this.g){for(var b=0;b<this.g.length;++b)q.h(this.g[b]);this.g=null}};
var q=new a;e.prototype.C=function(b){var d=this.j();b.m(d.resolve,d.reject)};e.prototype.D=function(b,d){var g=this.j();try{b.call(d,g.resolve,g.reject)}catch(k){g.reject(k)}};e.prototype.then=function(b,d){function g(m,p){return"function"==typeof m?function(x){try{k(m(x))}catch(y){l(y)}}:p}var k,l,z=new e(function(m,p){k=m;l=p});this.m(g(b,k),g(d,l));return z};e.prototype.catch=function(b){return this.then(void 0,b)};e.prototype.m=function(b,d){function g(){switch(k.h){case 1:b(k.i);break;case 2:d(k.i);
break;default:throw Error("Unexpected state: "+k.h);}}var k=this;null==this.g?q.h(g):this.g.push(g);this.s=!0};e.resolve=f;e.reject=function(b){return new e(function(d,g){g(b)})};e.race=function(b){return new e(function(d,g){for(var k=w(b),l=k.next();!l.done;l=k.next())f(l.value).m(d,g)})};e.all=function(b){var d=w(b),g=d.next();return g.done?f([]):new e(function(k,l){function z(x){return function(y){m[x]=y;p--;0==p&&k(m)}}var m=[],p=0;do m.push(void 0),p++,f(g.value).m(z(m.length-1),l),g=d.next();
while(!g.done)})};return e});var A=this||self,B=function(c,a){function f(){}f.prototype=a.prototype;c.I=a.prototype;c.prototype=new f;c.prototype.constructor=c;c.H=function(h,e,q){for(var b=Array(arguments.length-2),d=2;d<arguments.length;d++)b[d-2]=arguments[d];return a.prototype[e].apply(h,b)}},C=function(c){return c};function D(c){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{var a=Error().stack;a&&(this.stack=a)}c&&(this.message=String(c))}B(D,Error);D.prototype.name="CustomError";var E=function(c,a){c=c.split("%s");for(var f="",h=c.length-1,e=0;e<h;e++)f+=c[e]+(e<a.length?a[e]:"%s");D.call(this,f+c[h])};B(E,D);E.prototype.name="AssertionError";var F=function(c,a){throw new E("Failure"+(c?": "+c:""),Array.prototype.slice.call(arguments,1));};var G;var J=function(c,a){this.g=c===H&&a||"";this.h=I};J.prototype.toString=function(){return"Const{"+this.g+"}"};var I={},H={};var L=function(c,a){this.g=a===K?c:""};L.prototype.toString=function(){return this.g+""};var K={};var M=function(c){var a=new J(H,"https://apis.google.com/js/client.js");a instanceof J&&a.constructor===J&&a.h===I?a=a.g:(F("expected object of type Const, got '"+a+"'"),a="type_error:Const");if(void 0===G){var f=null;var h=A.trustedTypes;if(h&&h.createPolicy){try{f=h.createPolicy("goog#html",{createHTML:C,createScript:C,createScriptURL:C})}catch(q){A.console&&A.console.error(q.message)}G=f}else G=f}a=(f=G)?f.createScriptURL(a):a;a=new L(a,K);a instanceof L&&a.constructor===L?a=a.g:(f=typeof a,F("expected object of type TrustedResourceUrl, got '"+
a+"' of type "+("object"!=f?f:a?Array.isArray(a)?"array":f:"null")),a="type_error:TrustedResourceUrl");c.src=a;var e;a=(c.ownerDocument&&c.ownerDocument.defaultView||window).document;(e=(a=null===(e=a.querySelector)||void 0===e?void 0:e.call(a,"script[nonce]"))?a.nonce||a.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",e)};var N=function(){var c=document;var a="SCRIPT";"application/xhtml+xml"===c.contentType&&(a=a.toLowerCase());return c.createElement(a)};function O(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");P()}var P,Q=null,R=window;
function S(){if(Q)return Q;window.performance.mark("gapi_load_start");var c=R.colabExperiments&&R.colabExperiments.first_party_auth;return Q=new Promise(function(a,f){P=a;R.gapi_onload=function(){c?P():gapi.load("auth:client",O)};var h=N();M(h);h.async=!0;h.onerror=function(){f(Error("Error loading "+h.src))};a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(h,a)})}R.colab_gapi_loader={load:S};S().then(function(){},function(){});
